name: CI pull_request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        make do_pytest
    - name: Merge branch
      if: ${{ success() }}
      run: |
        git merge --no-ff ${{ github.event.pull_request.head.ref }}